services:
  - type: web
    name: citygazette
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn citygazette.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: citygazette.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
